### PR TITLE
test(mps-legacy-sync-plugin): Fix tests to make them run with `modelix.core` 8.x.x

### PR DESCRIPTION
**Pull request by odzhychko**
Also enabled test again.

### CODE REVIEW

**Comment by odzhychko** [comment]
Blocked by fix https://github.com/modelix/modelix.core/pull/795

**Review by benedekh — DISMISSED** [review]

**Comment by odzhychko** [comment]
Do not merge until https://github.com/modelix/modelix.core/pull/795 is fixed and we used the resulting Modelix version here.

**Comment by benedekh** [comment]
> Do not merge until https://github.com/modelix/modelix.core/pull/795 is fixed and we used the resulting Modelix version here.

**Suggestion:** please bump modelix version to 8.1.2, so your fix is included.

**Review by benedekh — APPROVED** [review]

**Pull request merged**
